FROM python:alpine3.8
RUN apk update
RUN apk add --no-cache --virtual .build-deps gcc musl-dev
RUN pip install --upgrade pip
RUN pip install numpy
WORKDIR /
RUN mkdir /hft
COPY dataloader /hft/dataloader
COPY utils /hft/utils
RUN pip install -r /hft/dataloader/requirements.txt
ENV PYTHONPATH "${PYTHONPATH}:/usr/lib/python3.7/site-packages:/"
EXPOSE 9000
EXPOSE 13000
ARG HOST
ARG PASSWORD
ENTRYPOINT python /hft/dataloader/loader.py --host=${HOST} --password=${PASSWORD}