version: '3'

services:
  server:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-storage/:/var/lib/clickhouse
  dataloader:
    build:
      dockerfile: ../Dockerfile-dataloader
      context: hft/
    depends_on:
      - server
    environment:
      HOST: server
      PASSWORD:
    logging:
      driver: "json-file"
      options:
        max-size: "3m"

volumes:
  clickhouse-storage:

