version: '3'

services:
  server:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse_storage/:/var/lib/clickhouse
  dataloader:
    image: evgerher/thesis-dataloader:0.1.3
    depends_on:
      - server
    environment:
      HOST: server
      PASSWORD:
    logging:
      driver: "json-file"
      options:
        max-size: "3m"

