version: '3'

services:
  server:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
#    volumes:
#      - $HOME/clickhouse_storage/:/var/lib/clickhouse
#  client:
#    image: yandex/clickhouse-client
#    depends_on:
#      - server
#    ports:
#      - "10000:10000"
  dataloader:
    image: evgerher/thesis-dataloader:0.0.3
    depends_on:
      - server
    environment:
      HOST: server
      PASSWORD:
